export { useAutenticacaoService } from './useAutenticacaoService'
export { useInstitutionService } from './useInstitutionService'
export { useLocalStorage } from './useLocalStorage'
export { useOrderService } from './useOrderService'
export { useItemOrderService } from './useItemOrderService'
export { useItemService } from './useItemService'
export { useServiceService } from './useServiceService'
export { useServiceOrderService } from './useServiceOrderService'
export { useProductOrderService } from './useProductOrderService'
export { useUrgentOrders } from './useUrgentOrdersService'
export { useInterestService } from './useInterestService'
export { useNewItemSevice } from './useNewItemService'
export { useItemSolicitationService } from './useItemSolicitationService'
export { useServiceSolicitationService } from './useServiceSolicitationService'

